allianceauth/srp/urls.py
from django.conf.urls import url

from . import views

app_name = 'srp'

urlpatterns = [
    # SRP URLS
    url(r'^$', views.srp_management, name='management'),
    url(r'^all/$', views.srp_management, {'all': True}, name='all'),
    url(r'^(\w+)/view$', views.srp_fleet_view, name='fleet'),
    url(r'^add/$', views.srp_fleet_add_view, name='add'),
    url(r'^(\w+)/edit$', views.srp_fleet_edit_view, name='edit'),
    url(r'^(\w+)/request', views.srp_request_view, name='request'),

    # SRP URLS
    url(r'^(\w+)/remove$', views.srp_fleet_remove, name='remove'),
    url(r'^(\w+)/disable$', views.srp_fleet_disable, name='disable'),
    url(r'^(\w+)/enable$', views.srp_fleet_enable, name='enable'),
    url(r'^(\w+)/complete$', views.srp_fleet_mark_completed,
        name='mark_completed'),
    url(r'^(\w+)/incomplete$', views.srp_fleet_mark_uncompleted,
        name='mark_uncompleted'),
    url(r'^request/remove/', views.srp_request_remove,
        name="request_remove"),
    url(r'^request/approve/', views.srp_request_approve,
        name='request_approve'),
    url(r'^request/reject/', views.srp_request_reject,
        name='request_reject'),
    url(r'^request/(\w+)/update', views.srp_request_update_amount,
        name="request_update_amount"),
]

allianceauth/urls.py
import esi.urls

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

import allianceauth.authentication.views
import allianceauth.authentication.urls
import allianceauth.notifications.urls
import allianceauth.groupmanagement.urls
import allianceauth.services.urls
from allianceauth.authentication.decorators import main_character_required, decorate_url_patterns
from allianceauth import NAME
from allianceauth import views
from allianceauth.authentication import hmac_urls
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Authentication
    url(r'', include(allianceauth.authentication.urls)),
    url(r'^account/login/$', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    url(r'^account/', include(hmac_urls)),

    # Admin urls
    url(r'^admin/', admin.site.urls),

    # SSO
    url(r'^sso/', include((esi.urls, 'esi'), namespace='esi')),
    url(r'^sso/login$', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    url(r'', include(allianceauth.notifications.urls)),

    # Groups
    url(r'', include(allianceauth.groupmanagement.urls)),

    # Services
    url(r'', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    url(r'^night/', views.NightModeRedirectView.as_view(), name='nightmode')
]


# Append app urls
app_urls = get_hooks('url_hook')
for app in app_urls:
    urlpatterns += [url(r'', decorate_url_patterns([app().include_pattern], main_character_required))]

allianceauth/srp/models.py
from django.db import models
from django.utils import timezone

from allianceauth.eveonline.models import EveCharacter


class SrpFleetMain(models.Model):
    fleet_name = models.CharField(max_length=254, default="")
    fleet_doctrine = models.CharField(max_length=254, default="")
    fleet_time = models.DateTimeField()
    fleet_srp_code = models.CharField(max_length=254, default="")
    fleet_srp_status = models.CharField(max_length=254, default="")
    fleet_commander = models.ForeignKey(EveCharacter, null=True, on_delete=models.SET_NULL)
    fleet_srp_aar_link = models.CharField(max_length=254, default="")

    def __str__(self):
        return self.fleet_name

    @property
    def total_cost(self):
        return sum([int(r.srp_total_amount) for r in self.srpuserrequest_set.all()])

    @property
    def pending_requests(self):
        return self.srpuserrequest_set.filter(srp_status='Pending').count()

    class Meta:
        permissions = (('access_srp', 'Can access SRP module'),)


class SrpUserRequest(models.Model):
    SRP_STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    )

    killboard_link = models.CharField(max_length=254, default="")
    after_action_report_link = models.CharField(max_length=254, default="")
    additional_info = models.CharField(max_length=254, default="")
    srp_status = models.CharField(max_length=8, default="Pending", choices=SRP_STATUS_CHOICES)
    srp_total_amount = models.BigIntegerField(default=0)
    character = models.ForeignKey(EveCharacter, null=True, on_delete=models.SET_NULL)
    srp_fleet_main = models.ForeignKey(SrpFleetMain, on_delete=models.CASCADE)
    kb_total_loss = models.BigIntegerField(default=0)
    srp_ship_name = models.CharField(max_length=254, default="")
    post_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.character.character_name + ' SRP request for ' + self.srp_ship_name

allianceauth/srp/views.py
import logging
import uuid

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.humanize.templatetags.humanize import intcomma
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.db.models import Sum
from allianceauth.eveonline.providers import provider
from allianceauth.notifications import notify
from .form import SrpFleetMainForm
from .form import SrpFleetMainUpdateForm
from .form import SrpFleetUserRequestForm
from .models import SrpFleetMain
from .models import SrpUserRequest
from .managers import SRPManager

logger = logging.getLogger(__name__)


def random_string(string_length=10):
    """Returns a random string of length string_length."""
    random = str(uuid.uuid4())  # Convert UUID format to a Python string.
    random = random.upper()  # Make all characters uppercase.
    random = random.replace("-", "")  # Remove the UUID '-'.
    return random[0:string_length]  # Return the random string.


@login_required
@permission_required('srp.access_srp')
def srp_management(request, all=False):
    logger.debug("srp_management called by user %s" % request.user)
    fleets = SrpFleetMain.objects.select_related('fleet_commander').prefetch_related('srpuserrequest_set').all()
    if not all:
        fleets = fleets.filter(fleet_srp_status="")
    else:
        logger.debug("Returning all SRP requests")
    totalcost = fleets.aggregate(total_cost=Sum('srpuserrequest__srp_total_amount')).get('total_cost', 0)
    context = {"srpfleets": fleets, "totalcost": totalcost}
    return render(request, 'srp/management.html', context=context)

@login_required
@permission_required('srp.access_srp')
def srp_fleet_view(request, fleet_id):
    logger.debug("srp_fleet_view called by user %s for fleet id %s" % (request.user, fleet_id))
    try:
        fleet_main = SrpFleetMain.objects.get(id=fleet_id)
    except SrpFleetMain.DoesNotExist:
        raise Http404
    context = {"fleet_id": fleet_id, "fleet_status": fleet_main.fleet_srp_status,
               "srpfleetrequests": fleet_main.srpuserrequest_set.select_related('character').order_by('srp_ship_name'),
               "totalcost": fleet_main.total_cost}

    return render(request, 'srp/data.html', context=context)


@login_required
@permission_required('auth.srp_management')
def srp_fleet_add_view(request):
    logger.debug("srp_fleet_add_view called by user %s" % request.user)
    completed = False
    completed_srp_code = ""

    if request.method == 'POST':
        form = SrpFleetMainForm(request.POST)
        logger.debug("Request type POST contains form valid: %s" % form.is_valid())
        if form.is_valid():
            srp_fleet_main = SrpFleetMain()
            srp_fleet_main.fleet_name = form.cleaned_data['fleet_name']
            srp_fleet_main.fleet_doctrine = form.cleaned_data['fleet_doctrine']
            srp_fleet_main.fleet_time = form.cleaned_data['fleet_time']
            srp_fleet_main.fleet_srp_code = random_string(8)
            srp_fleet_main.fleet_commander = request.user.profile.main_character

            srp_fleet_main.save()

            completed = True
            completed_srp_code = srp_fleet_main.fleet_srp_code
            logger.info("Created SRP Fleet %s by user %s" % (srp_fleet_main.fleet_name, request.user))
            messages.success(request, _('Created SRP fleet %(fleetname)s.') % {"fleetname": srp_fleet_main.fleet_name})

    else:
        logger.debug("Returning blank SrpFleetMainForm")
        form = SrpFleetMainForm()

    render_items = {'form': form, "completed": completed, "completed_srp_code": completed_srp_code}

    return render(request, 'srp/add.html', context=render_items)


@login_required
@permission_required('auth.srp_management')
def srp_fleet_remove(request, fleet_id):
    logger.debug("srp_fleet_remove called by user %s for fleet id %s" % (request.user, fleet_id))
    srpfleetmain = get_object_or_404(SrpFleetMain, id=fleet_id)
    srpfleetmain.delete()
    logger.info("SRP Fleet %s deleted by user %s" % (srpfleetmain.fleet_name, request.user))
    messages.success(request, _('Removed SRP fleet %(fleetname)s.') % {"fleetname": srpfleetmain.fleet_name})
    return redirect("srp:management")


@login_required
@permission_required('auth.srp_management')
def srp_fleet_disable(request, fleet_id):
    logger.debug("srp_fleet_disable called by user %s for fleet id %s" % (request.user, fleet_id))
    srpfleetmain = get_object_or_404(SrpFleetMain, id=fleet_id)
    srpfleetmain.fleet_srp_code = ""
    srpfleetmain.save()
    logger.info("SRP Fleet %s disabled by user %s" % (srpfleetmain.fleet_name, request.user))
    messages.success(request, _('Disabled SRP fleet %(fleetname)s.') % {"fleetname": srpfleetmain.fleet_name})
    return redirect("srp:management")


@login_required
@permission_required('auth.srp_management')
def srp_fleet_enable(request, fleet_id):
    logger.debug("srp_fleet_enable called by user %s for fleet id %s" % (request.user, fleet_id))
    srpfleetmain = get_object_or_404(SrpFleetMain, id=fleet_id)
    srpfleetmain.fleet_srp_code = random_string(8)
    srpfleetmain.save()
    logger.info("SRP Fleet %s enable by user %s" % (srpfleetmain.fleet_name, request.user))
    messages.success(request, _('Enabled SRP fleet %(fleetname)s.') % {"fleetname": srpfleetmain.fleet_name})
    return redirect("srp:management")


@login_required
@permission_required('auth.srp_management')
def srp_fleet_mark_completed(request, fleet_id):
    logger.debug("srp_fleet_mark_completed called by user %s for fleet id %s" % (request.user, fleet_id))
    srpfleetmain = get_object_or_404(SrpFleetMain, id=fleet_id)
    srpfleetmain.fleet_srp_status = "Completed"
    srpfleetmain.save()
    logger.info("Marked SRP Fleet %s as completed by user %s" % (srpfleetmain.fleet_name, request.user))
    messages.success(request,
                     _('Marked SRP fleet %(fleetname)s as completed.') % {"fleetname": srpfleetmain.fleet_name})
    return redirect("srp:fleet", fleet_id)


@login_required
@permission_required('auth.srp_management')
def srp_fleet_mark_uncompleted(request, fleet_id):
    logger.debug("srp_fleet_mark_uncompleted called by user %s for fleet id %s" % (request.user, fleet_id))
    srpfleetmain = get_object_or_404(SrpFleetMain, id=fleet_id)
    srpfleetmain.fleet_srp_status = ""
    srpfleetmain.save()
    logger.info("Marked SRP Fleet %s as incomplete for user %s" % (fleet_id, request.user))
    messages.success(request,
                     _('Marked SRP fleet %(fleetname)s as incomplete.') % {"fleetname": srpfleetmain.fleet_name})
    return redirect("srp:fleet", fleet_id)


@login_required
@permission_required('srp.access_srp')
def srp_request_view(request, fleet_srp):
    logger.debug("srp_request_view called by user %s for fleet srp code %s" % (request.user, fleet_srp))

    if SrpFleetMain.objects.filter(fleet_srp_code=fleet_srp).exists() is False:
        logger.error("Unable to locate SRP Fleet using code %s for user %s" % (fleet_srp, request.user))
        messages.error(request,
                       _('Unable to locate SRP code with ID %(srpfleetid)s') % {"srpfleetid": fleet_srp})
        return redirect("srp:management")

    if request.method == 'POST':
        form = SrpFleetUserRequestForm(request.POST)
        logger.debug("Request type POST contains form valid: %s" % form.is_valid())

        if form.is_valid():
            if SrpUserRequest.objects.filter(killboard_link=form.cleaned_data['killboard_link']).exists():
                messages.error(request,
                               _("This Killboard link has already been posted."))
                return redirect("srp:management")

            character = request.user.profile.main_character
            srp_fleet_main = SrpFleetMain.objects.get(fleet_srp_code=fleet_srp)
            post_time = timezone.now()

            srp_request = SrpUserRequest()
            srp_request.killboard_link = form.cleaned_data['killboard_link']
            srp_request.additional_info = form.cleaned_data['additional_info']
            srp_request.character = character
            srp_request.srp_fleet_main = srp_fleet_main

            try:
                srp_kill_link = SRPManager.get_kill_id(srp_request.killboard_link)
                (ship_type_id, ship_value, victim_id) = SRPManager.get_kill_data(srp_kill_link)
            except ValueError:
                logger.debug("User %s Submitted Invalid Killmail Link %s or server could not be reached" % (
                    request.user, srp_request.killboard_link))
                # THIS SHOULD BE IN FORM VALIDATION
                messages.error(request,
                               _(
                                   "Your SRP request Killmail link is invalid. Please make sure you are using zKillboard."))
                return redirect("srp:management")

            if request.user.character_ownerships.filter(character__character_id=str(victim_id)).exists():
                srp_request.srp_ship_name = provider.get_itemtype(ship_type_id).name
                srp_request.kb_total_loss = ship_value
                srp_request.post_time = post_time
                srp_request.save()
                logger.info("Created SRP Request on behalf of user %s for fleet name %s" % (
                    request.user, srp_fleet_main.fleet_name))
                messages.success(request,
                                 _('Submitted SRP request for your %(ship)s.') % {"ship": srp_request.srp_ship_name})
                return redirect("srp:management")
            else:
                messages.error(request,
                               _(

allianceauth/srp/templates/srp/data.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% load humanize %}
{% block page_title %}Srp Fleet Data{% endblock page_title %}
{% block extra_css %}
  {% include 'bundles/x-editable.css.html' %}
  <link href="{% static 'css/checkbox.css' %}" rel="stylesheet" type="text/css">
  <style>
  .radio label, .checkbox label {
      padding-left: 10px;
  }
  .editable {
    width:150px;
    text-align: center;
  }
  .editableform .form-control {
      width: 95%;
      text-align: center;
      margin-left: 10px;
  }

  .editable-input {
      width: 95%;
  }
  .radio, .checkbox {
      margin-top: 0px;
      margin-bottom: 0px;
  }
  .editable-error-block {
      white-space: nowrap;
  }
  .editable-click, a.editable-click, a.editable-click:hover {
      border-bottom: none;
  }
  .tooltip-inner {
    white-space:pre;
    max-width: none;
  }
  </style>
{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <div class="row">
            <h1 class="page-header text-center">{% trans "SRP Fleet Data" %}
                <div class="text-right">
                    {% if perms.auth.srp_management %}
                        {% if fleet_status == "Completed" %}
                            <a href="{% url 'srp:mark_uncompleted' fleet_id %}" class="btn btn-warning">
                                {% trans "Mark Incomplete" %}
                            </a>
                        {% else %}
                            <a href="{% url 'srp:mark_completed' fleet_id %}" class="btn btn-success">
                                {% trans "Mark Completed" %}
                            </a>
                        {% endif %}
                    {% endif %}
                </div>
            </h1>
            
            {% if srpfleetrequests %}
            <form method="POST">
                {% csrf_token %}
                <div class="alert alert-info" role="alert">
                    <div class="text-right">
                        <b><span style="padding-right:2.5em">{% trans "Total Losses:" %} {{ srpfleetrequests.count }}</span></b>
                        <b><span style="padding-right:2.5em">{% trans "Total ISK Cost:" %} {{ totalcost | intcomma }}</span></b>
                        {% if perms.auth.srp_management %}
                            <button type="submit" title="Approve" class="btn btn-success" formaction="{% url 'srp:request_approve' %}">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button>
                            <button type="submit" title="Reject" class="btn btn-warning" formaction="{% url 'srp:request_reject' %}">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            <button type="submit" title="Remove" onclick="return confirm('{% trans "Are you sure you want to delete SRP requests?" %}')" class="btn btn-danger" formaction="{% url 'srp:request_remove' %}">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        {% endif %}
                    </div>
                </div>
            
                <table class="table">
                    <tr>
                        <th class="text-center">{% trans "Pilot Name" %}</th>
                        <th class="text-center">{% trans "Killboard Link" %}</th>
                        <th class="text-center">{% trans "Additional Info" %}</th>
                        <th class="text-center">{% trans "Ship Type" %}</th>
                        <th class="text-center">{% trans "Killboard Loss Amt" %}</th>
                        <th class="text-center">{% trans "SRP ISK Cost" %}
                        {% blocktrans %}<i class="glyphicon glyphicon-question-sign" rel="tooltip" title="Click value to edit
Enter to save&next
ESC to cancel"
                        id="blah"></i></th>{% endblocktrans %}
                        <th class="text-center">{% trans "Post Time" %}</th>
                        <th class="text-center">{% trans "Status" %}</th>
                        {% if perms.auth.srp_management %}
                            <th class="text-center">{% trans "Actions" %}</th>
                        {% endif %}
                    </tr>
                    {% for srpfleetrequest in srpfleetrequests %}
                        <tr>
                            <td class="text-center">{{ srpfleetrequest.character.character_name }}</td>
                            <td class="text-center">
                                <a href="{{ srpfleetrequest.killboard_link }}"
                                   target="_blank" class="label label-warning">Link</a>
                            </td>
                            <td class="text-center">{{ srpfleetrequest.additional_info }}</td>
                            <td class="text-center">{{ srpfleetrequest.srp_ship_name }}</td>
                            <td class="text-center">{{ srpfleetrequest.kb_total_loss | intcomma }} ISK</td>
                            <td class="srp" data-name="srp_total_amount" data-type="number" data-pk="{{srpfleetrequest.id}}" data-url="{% url 'srp:request_update_amount' srpfleetrequest.id %}" data-params="{csrfmiddlewaretoken:'{{csrf_token}}'}" class="text-center">{{ srpfleetrequest.srp_total_amount | intcomma }} ISK</td>
                            <td class="text-center">{{ srpfleetrequest.post_time | date:"Y-m-d H:i" }}</td>
                            <td class="text-center">
                                {% if srpfleetrequest.srp_status == "Approved" %}
                                    <div class="label label-success">
                                        {% trans "Approved" %}
                                    </div>
                                {% elif srpfleetrequest.srp_status == "Rejected" %}
                                    <div class="label label-danger">
                                        {% trans "Rejected" %}
                                    </div>
                                {% else %}
                                    <div class="label label-warning">
                                        {% trans "Pending" %}
                                    </div>
                                {% endif %}
                            </td>
                            {% if perms.auth.srp_management %}
                                <td class="text-center">
                                    <div class="checkbox">
                                        <label style="font-size: 1.5em">
                                            <input type="checkbox" name="{{srpfleetrequest.id}}">
                                            <span class="cr"><i class="cr-icon fa fa-check"></i></span>
                                        </label>
                                    </div>                            
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}   
                </table>
                <div class="alert alert-info" role="alert">
                    <div class="text-right">
                        <b><span style="padding-right:2.5em">{% trans "Total Losses:" %} {{ srpfleetrequests.count }}</span></b>
                        <b><span style="padding-right:2.5em">{% trans "Total ISK Cost:" %} {{ totalcost | intcomma }}</span></b>
                        {% if perms.auth.srp_management %}
                            <button type="submit" title="Approve" class="btn btn-success" formaction="{% url 'srp:request_approve' %}">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button>
                            <button type="submit" title="Reject" class="btn btn-warning" formaction="{% url 'srp:request_reject' %}">
                                <span class="glyphicon glyphicon-remove"></span>
                            </button>
                            <button type="submit" title="Remove" onclick="return confirm('{% trans "Are you sure you want to delete SRP requests?" %}')" class="btn btn-danger" formaction="{% url 'srp:request_remove' %}">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        {% endif %}
                    </div>
                </div>
            </form>
            {% else %}
            <div class="alert alert-warning text-center">{% trans "No SRP requests for this fleet." %}</div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/x-editable-js.html' %}
{% endblock %}

{% block extra_script %}
  $(document).ready(function() {
      $.fn.editable.defaults.mode = 'inline';
      $.fn.editable.defaults.showbuttons = false;
      $.fn.editable.defaults.highlight = "#AAFF80";


      $('.srp').editable({
          display: function(value, response) {
              return false;
          },
          success: function(response, newValue) {
              newValue = parseInt(newValue);
              newvalue = newValue.toLocaleString() + " ISK";
              $(this).html(newvalue.bold());
          },
          validate: function(value) {
              if (value === null || value === '') {
                  return 'Empty values not allowed';
              }
          }
      });
      $('.srp').on('hidden', function(e, reason){
              if(reason === 'save' || reason === 'nochange') {
              var $next = $(this).closest('tr').next().find('.editable');
              setTimeout(function() {
                  $next.editable('show');
              }, 400); 
          }
     });
  });
  $(document).ready(function(){
    $("[rel=tooltip]").tooltip({ placement: 'top'});
});
{% endblock extra_script %}

allianceauth/srp/templates/srp/management.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% load humanize %}

{% block page_title %}{% trans "Srp Management" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <div class="row">
            <h1 class="page-header text-center">{% trans "SRP Management" %}
                <div class="text-right">
                    {% if perms.auth.srp_management %}
                        <a href="{% url 'srp:all' %}" class="btn btn-primary">
                            {% trans "View All" %}
                        </a>
                        <a href="{% url 'srp:add' %}" class="btn btn-success">
                            {% trans "Add SRP Fleet" %}
                        </a>
                    {% endif %}
                </div>
            </h1>
            <div class="alert alert-info" role="alert">
                <div class="text-right">
                    <b>{% trans "Total ISK Cost:" %} {{ totalcost | intcomma }}</b>
                </div>
            </div>
            {% if srpfleets %}
            <table class="table">
                <tr>
                    <th class="text-center">{% trans "Fleet Name" %}</th>
                    <th class="text-center">{% trans "Fleet Time" %}</th>
                    <th class="text-center">{% trans "Fleet Doctrine" %}</th>
                    <th class="text-center">{% trans "Fleet Commander" %}</th>
                    <th class="text-center">{% trans "Fleet AAR" %}</th>
                    <th class="text-center">{% trans "Fleet SRP Code" %}</th>
                    <th class="text-center">{% trans "Fleet ISK Cost" %}</th>
                    <th class="text-center">{% trans "SRP Status" %}</th>
                    <th class="text-center">{% trans "Pending Requests" %}</th>
                    <th width="100px" class="text-center">{% trans "Actions" %}</th>
                </tr>
                {% for srpfleet in srpfleets %}
                    <tr>
                        <td class="text-center">
                            <div class="label label-info">
                                {{ srpfleet.fleet_name }}
                            </div>
                        </td>
                        <td class="text-center">{{ srpfleet.fleet_time | date:"Y-m-d H:i" }}</td>
                        <td class="text-center">{{ srpfleet.fleet_doctrine }}</td>
                        <td class="text-center">
                            <div class="label label-success">
                                {{ srpfleet.fleet_commander.character_name }}
                            </div>
                        </td>
                        <td class="text-center">
                            {%  if srpfleet.fleet_srp_aar_link %}
                                <a href="{{ srpfleet.fleet_srp_aar_link }}" target="_blank" class="label label-primary">{% trans 'Link' %}</a>
                            {%  endif %}
                        </td>
                        <td class="text-center">
                            {% if srpfleet.fleet_srp_code %}
                                <a class="label label-warning" href="{% url 'srp:request' srpfleet.fleet_srp_code %}">{{ srpfleet.fleet_srp_code }}</a>
                            {% else %}
                                <div class="label label-danger">
                                    {% trans "Disabled" %}
                                </div>
                            {% endif %}
                        </td>
                        <td class="text-center">ISK: {{ srpfleet.total_cost | intcomma }}</td>

                        <td class="text-center">
                            {% if srpfleet.fleet_srp_status == "" %}
                                <div class="label label-warning">
                                    {% trans "Pending" %}
                                </div>
                            {% else %}
                                <div class="label label-success">
                                    {% trans "Completed" %}
                                </div>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <div class="label label-warning">{{ srpfleet.pending_requests }}</div>
                        </td>
                        <td class="text-center">

                            <a href="{% url 'srp:fleet' srpfleet.id %}" class="btn btn-primary" title="View">
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </a>

                            {% if perms.auth.srp_management %}
                                <a href="{% url 'srp:edit' srpfleet.id %}" class="btn btn-info" title="Edit">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>

                                <a href="{% url 'srp:remove' srpfleet.id %}" onclick="return confirm('{% trans "Are you sure you want to delete this SRP code and its contents?" %}')" class="btn btn-danger" title="Remove">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                                {% if srpfleet.fleet_srp_code %}
                                    <a href="{% url 'srp:disable' srpfleet.id %}" class="btn btn-warning" title="Disable">
                                        <span class="glyphicon glyphicon-remove-sign"></span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'srp:enable' srpfleet.id %}" class="btn btn-success" title="Enable">
                                        <span class="glyphicon glyphicon-ok-sign"></span>
                                    </a>
                                {% endif %}

                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
            <div class="alert alert-warning text-center">{% trans "No SRP fleets created." %}</div>
            {% endif %}
        </div>
    </div>

{% endblock content %}