allianceauth/hrapplications/urls.py
from django.conf.urls import url

from . import views

app_name = 'hrapplications'

urlpatterns = [
    url(r'^$', views.hr_application_management_view,
        name="index"),
    url(r'^create/$', views.hr_application_create_view,
        name="create_view"),
    url(r'^create/(\d+)', views.hr_application_create_view,
        name="create_view"),
    url(r'^remove/(\w+)', views.hr_application_remove,
        name="remove"),
    url(r'^view/(\w+)', views.hr_application_view,
        name="view"),
    url(r'^personal/view/(\w+)', views.hr_application_personal_view,
        name="personal_view"),
    url(r'^personal/removal/(\w+)',
        views.hr_application_personal_removal,
        name="personal_removal"),
    url(r'^approve/(\w+)', views.hr_application_approve,
        name="approve"),
    url(r'^reject/(\w+)', views.hr_application_reject,
        name="reject"),
    url(r'^search/', views.hr_application_search,
        name="search"),
    url(r'^mark_in_progress/(\w+)', views.hr_application_mark_in_progress,
        name="mark_in_progress"),
    ]

allianceauth/urls.py
import esi.urls

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

import allianceauth.authentication.views
import allianceauth.authentication.urls
import allianceauth.notifications.urls
import allianceauth.groupmanagement.urls
import allianceauth.services.urls
from allianceauth.authentication.decorators import main_character_required, decorate_url_patterns
from allianceauth import NAME
from allianceauth import views
from allianceauth.authentication import hmac_urls
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Authentication
    url(r'', include(allianceauth.authentication.urls)),
    url(r'^account/login/$', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    url(r'^account/', include(hmac_urls)),

    # Admin urls
    url(r'^admin/', admin.site.urls),

    # SSO
    url(r'^sso/', include((esi.urls, 'esi'), namespace='esi')),
    url(r'^sso/login$', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    url(r'', include(allianceauth.notifications.urls)),

    # Groups
    url(r'', include(allianceauth.groupmanagement.urls)),

    # Services
    url(r'', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    url(r'^night/', views.NightModeRedirectView.as_view(), name='nightmode')
]


# Append app urls
app_urls = get_hooks('url_hook')
for app in app_urls:
    urlpatterns += [url(r'', decorate_url_patterns([app().include_pattern], main_character_required))]

allianceauth/hrapplications/models.py
from django.contrib.auth.models import User
from django.db import models
from sortedm2m.fields import SortedManyToManyField

from allianceauth.eveonline.models import EveCharacter
from allianceauth.eveonline.models import EveCorporationInfo


class ApplicationQuestion(models.Model):
    title = models.CharField(max_length=254, verbose_name='Question')
    help_text = models.CharField(max_length=254, blank=True, null=True)
    multi_select = models.BooleanField(default=False)

    def __str__(self):
        return "Question: " + self.title


class ApplicationChoice(models.Model):
    question = models.ForeignKey(ApplicationQuestion,on_delete=models.CASCADE,related_name="choices")
    choice_text = models.CharField(max_length=200, verbose_name='Choice')

    def __str__(self):
        return self.choice_text

class ApplicationForm(models.Model):
    questions = SortedManyToManyField(ApplicationQuestion)
    corp = models.OneToOneField(EveCorporationInfo, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.corp)


class Application(models.Model):
    form = models.ForeignKey(ApplicationForm, on_delete=models.CASCADE, related_name='applications')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')
    approved = models.NullBooleanField(blank=True, null=True, default=None)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    reviewer_character = models.ForeignKey(EveCharacter, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " Application To " + str(self.form)

    class Meta:
        permissions = (
            ('approve_application', 'Can approve applications'), ('reject_application', 'Can reject applications'),
            ('view_apis', 'Can view applicant APIs'),)
        unique_together = ('form', 'user')

    @property
    def main_character(self):
        return self.user.profile.main_character

    @property
    def characters(self):
        return [o.character for o in self.user.character_ownerships.all()]

    @property
    def reviewer_str(self):
        if self.reviewer_character:
            return str(self.reviewer_character)
        elif self.reviewer:
            return "User " + str(self.reviewer)
        else:
            return None


class ApplicationResponse(models.Model):
    question = models.ForeignKey(ApplicationQuestion, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='responses')
    answer = models.TextField()

    def __str__(self):
        return str(self.application) + " Answer To " + str(self.question)

    class Meta:
        unique_together = ('question', 'application')


class ApplicationComment(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " comment on " + str(self.application)

allianceauth/hrapplications/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class HRApplicationCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea, required=False, label=_("Comment"))


class HRApplicationSearchForm(forms.Form):
    search_string = forms.CharField(max_length=254, required=True, label=_("Search String"))

allianceauth/hrapplications/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.db.models import Q
from .models import Application
from .models import ApplicationComment
from .models import ApplicationForm
from .models import ApplicationResponse
from allianceauth.notifications import notify

from .forms import HRApplicationCommentForm
from .forms import HRApplicationSearchForm

logger = logging.getLogger(__name__)


def create_application_test(user):
    return bool(user.profile.main_character)


@login_required
def hr_application_management_view(request):
    logger.debug("hr_application_management_view called by user %s" % request.user)
    corp_applications = []
    finished_corp_applications = []
    main_char = request.user.profile.main_character

    base_app_query = Application.objects.select_related('user', 'form', 'form__corp')
    if request.user.is_superuser:
        corp_applications = base_app_query.filter(approved=None).order_by('-created')
        finished_corp_applications = base_app_query.exclude(approved=None).order_by('-created')
    elif request.user.has_perm('auth.human_resources') and main_char:
        if ApplicationForm.objects.filter(corp__corporation_id=main_char.corporation_id).exists():
            app_form = ApplicationForm.objects.get(corp__corporation_id=main_char.corporation_id)
            corp_applications = base_app_query.filter(form=app_form).filter(approved=None).order_by('-created')
            finished_corp_applications = base_app_query.filter(form=app_form).filter(
                approved__in=[True, False]).order_by('-created')
    logger.debug("Retrieved %s personal, %s corp applications for %s" % (
        len(request.user.applications.all()), len(corp_applications), request.user))
    context = {
        'personal_apps': request.user.applications.all(),
        'applications': corp_applications,
        'finished_applications': finished_corp_applications,
        'search_form': HRApplicationSearchForm(),
        'create': create_application_test(request.user)
    }
    return render(request, 'hrapplications/management.html', context=context)


@login_required
@user_passes_test(create_application_test)
def hr_application_create_view(request, form_id=None):
    if form_id:
        app_form = get_object_or_404(ApplicationForm, id=form_id)
        if request.method == "POST":
            if Application.objects.filter(user=request.user).filter(form=app_form).exists():
                logger.warn("User %s attempting to duplicate application to %s" % (request.user, app_form.corp))
            else:
                application = Application(user=request.user, form=app_form)
                application.save()
                for question in app_form.questions.all():
                    response = ApplicationResponse(question=question, application=application)
                    response.answer = "\n".join(request.POST.getlist(str(question.pk),
                                                       ""))
                    response.save()
                logger.info("%s created %s" % (request.user, application))
            return redirect('hrapplications:personal_view', application.id)
        else:
            questions = app_form.questions.all()
            return render(request, 'hrapplications/create.html',
                          context={'questions': questions, 'corp': app_form.corp})
    else:
        choices = []
        for app_form in ApplicationForm.objects.all():
            if not Application.objects.filter(user=request.user).filter(form=app_form).exists():
                choices.append((app_form.id, app_form.corp.corporation_name))
        return render(request, 'hrapplications/corpchoice.html', context={'choices': choices})


@login_required
def hr_application_personal_view(request, app_id):
    logger.debug("hr_application_personal_view called by user %s for app id %s" % (request.user, app_id))
    app = get_object_or_404(Application, pk=app_id)
    if app.user == request.user:
        context = {
            'app': app,
            'responses': ApplicationResponse.objects.filter(application=app),
            'buttons': False,
            'comments': ApplicationComment.objects.filter(application=app),
            'comment_form': HRApplicationCommentForm(),
        }
        return render(request, 'hrapplications/view.html', context=context)
    else:
        logger.warn("User %s not authorized to view %s" % (request.user, app))
        return redirect('hrapplications:personal_view')


@login_required
def hr_application_personal_removal(request, app_id):
    logger.debug("hr_application_personal_removal called by user %s for app id %s" % (request.user, app_id))
    app = get_object_or_404(Application, pk=app_id)
    if app.user == request.user:
        if app.approved is None:
            logger.info("User %s deleting %s" % (request.user, app))
            app.delete()
        else:
            logger.warn("User %s attempting to delete reviewed app %s" % (request.user, app))
    else:
        logger.warn("User %s not authorized to delete %s" % (request.user, app))
    return redirect('hrapplications:index')


@login_required
@permission_required('auth.human_resources')
def hr_application_view(request, app_id):
    logger.debug("hr_application_view called by user %s for app id %s" % (request.user, app_id))
    try:
        app = Application.objects.prefetch_related('responses', 'comments', 'comments__user').get(pk=app_id)
    except Application.DoesNotExist:
        raise Http404
    if request.method == 'POST':
        if request.user.has_perm('hrapplications.add_applicationcomment'):
            form = HRApplicationCommentForm(request.POST)
            logger.debug("Request type POST contains form valid: %s" % form.is_valid())
            if form.is_valid():
                comment = ApplicationComment()
                comment.application = app
                comment.user = request.user
                comment.text = form.cleaned_data['comment']
                comment.save()
                logger.info("Saved comment by user %s to %s" % (request.user, app))
                return redirect('hrapplications:view', app_id)
        else:
            logger.warn("User %s does not have permission to add ApplicationComments" % request.user)
            return redirect('hrapplications:view', app_id)
    else:
        logger.debug("Returning blank HRApplication comment form.")
        form = HRApplicationCommentForm()
    context = {
        'app': app,
        'responses': app.responses.all(),
        'buttons': True,
        'comments': app.comments.all(),
        'comment_form': form,
    }
    return render(request, 'hrapplications/view.html', context=context)


@login_required
@permission_required('auth.human_resources')
@permission_required('hrapplications.delete_application')
def hr_application_remove(request, app_id):
    logger.debug("hr_application_remove called by user %s for app id %s" % (request.user, app_id))
    app = get_object_or_404(Application, pk=app_id)
    logger.info("User %s deleting %s" % (request.user, app))
    app.delete()
    notify(app.user, "Application Deleted", message="Your application to %s was deleted." % app.form.corp)
    return redirect('hrapplications:index')


@login_required
@permission_required('auth.human_resources')
@permission_required('hrapplications.approve_application')
def hr_application_approve(request, app_id):
    logger.debug("hr_application_approve called by user %s for app id %s" % (request.user, app_id))
    app = get_object_or_404(Application, pk=app_id)
    if request.user.is_superuser or request.user == app.reviewer:
        logger.info("User %s approving %s" % (request.user, app))
        app.approved = True
        app.save()
        notify(app.user, "Application Accepted", message="Your application to %s has been approved." % app.form.corp,
               level="success")
    else:
        logger.warn("User %s not authorized to approve %s" % (request.user, app))
    return redirect('hrapplications:index')


@login_required
@permission_required('auth.human_resources')
@permission_required('hrapplications.reject_application')
def hr_application_reject(request, app_id):
    logger.debug("hr_application_reject called by user %s for app id %s" % (request.user, app_id))
    app = get_object_or_404(Application, pk=app_id)
    if request.user.is_superuser or request.user == app.reviewer:
        logger.info("User %s rejecting %s" % (request.user, app))
        app.approved = False
        app.save()
        notify(app.user, "Application Rejected", message="Your application to %s has been rejected." % app.form.corp,
               level="danger")
    else:
        logger.warn("User %s not authorized to reject %s" % (request.user, app))
    return redirect('hrapplications:index')


@login_required
@permission_required('auth.human_resources')
def hr_application_search(request):
    logger.debug("hr_application_search called by user %s" % request.user)
    if request.method == 'POST':
        form = HRApplicationSearchForm(request.POST)
        logger.debug("Request type POST contains form valid: %s" % form.is_valid())
        if form.is_valid():
            searchstring = form.cleaned_data['search_string'].lower()
            applications = set([])
            logger.debug("Searching for application with character name %s for user %s" % (searchstring, request.user))
            app_list = Application.objects.all()
            if not request.user.is_superuser:
                try:
                    app_list = app_list.filter(
                        form__corp__corporation_id=request.user.profile.main_character.corporation_id)
                except AttributeError:
                    logger.warn(

allianceauth/hrapplications/templates/hrapplications/corpchoice.html
{% extends "allianceauth/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "Choose a Corp" %}{% endblock page_title %}
{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Choose a Corp" %}</h1>
        {% if choices %}
            <div class="panel panel-primary">
                <div class="panel-heading">{% trans "Available Corps" %}</div>
                <table class="table table-responsive">
                    {% for choice in choices %}
                        <tr>
                            <td class="text-center">
                                <a href="{% url 'hrapplications:create_view' choice.0 %}" class="btn btn-primary" title="Apply">{{ choice.1 }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        {% else %}
            <div class="alert alert-danger">{% trans "No corps are accepting applications at this time." %}</div>
        {% endif %}
    </div>
{% endblock content %}

allianceauth/hrapplications/templates/hrapplications/create.html
{% extends "allianceauth/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "Apply To" %} {{ corp.corporation_name }}{% endblock page_title %}
{% block content %}
<div class="col-lg-12">
    <h1 class="page-header text-center">{% trans "Apply To" %} {{ corp.corporation_name }}</h1>
    <div class="container-fluid">
        <div class="col-md-4 col-md-offset-4">
            <div class="row">
                <form class="form-signin">
                    {% csrf_token %}
                    {% for question in questions %}
                        <div class="form-group">
                            <label class="control-label" for="id_{{ question.pk }}">{{ question.title }}</label>
                            <div class=" ">
                            {% if question.help_text %}
                                <div cass="text-center">{{ question.help_text }}</div>
                            {% endif %}
                            {% for choice in question.choices.all %}
                                <input type={% if question.multi_select == False %}"radio"{% else %}"checkbox"{% endif %} name="{{ question.pk }}" id="id_{{ question.pk }}" value="{{ choice.choice_text }}" />
                                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                            {% empty %}
                                <textarea class="form-control" cols="30" id="id_{{ question.pk }}" name="{{ question.pk }}" rows="4"></textarea>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <button class="btn btn-lg btn-primary btn-block" type="submit" formmethod="post">{% trans "Submit" %}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

allianceauth/hrapplications/templates/hrapplications/management.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "HR Application Management" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Personal Applications" %}
            <div class="text-right">
                {% if create %}
                    <a href="{% url 'hrapplications:create_view' %}">
                        <button type="button" class="btn btn-success">{% trans "Create Application" %}</button>
                    </a>
                {% else %}
                    <button type="button" class="btn btn-success" disabled>{% trans "Create Application" %}</button>
                {% endif %}
            </div>
        </h1>
        {% if personal_apps %}
            <div class="panel panel-default">
                <table class="table table-condensed">
                    <tr>
                        <th class="text-center">{% trans "Username" %}</th>
                        <th class="text-center">{% trans "Corporation" %}
                        <th class="text-center">{% trans "Status" %}</th>
                        <th class="text-center">{% trans "Actions" %}</th>
                    </tr>
                    {% for personal_app in personal_apps %}
                        <tr>
                            <td class="text-center">{{ personal_app.user.username }}</td>
                            <td class="text-center">{{ personal_app.form.corp.corporation_name }}</td>
                            <td class="text-center">
                                {% if personal_app.approved == None %}
                                    <div class="label label-warning">{% trans "Pending" %}</div>
                                {% elif  personal_app.approved == True %}
                                    <div class="label label-success">{% trans "Approved" %}</div>
                                {% else %}
                                    <div class="label label-danger">{% trans "Rejected" %}</div>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'hrapplications:personal_view' personal_app.id %}"
                                   class="btn btn-primary">
                                    <span class="glyphicon glyphicon-eye-open"></span>
                                </a>

                                {% if personal_app.approved == None %}
                                    <a href="{% url 'hrapplications:personal_removal' personal_app.id %}"
                                       class="btn btn-danger">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        {% endif %}
        {% if perms.auth.human_resources %}
            <h1 class="page-header text-center">{% trans "Application Management" %}
                <div class="text-right">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
                        {% trans "Search Applications" %}
                    </button>
                </div>
            </h1>
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#pending">{% trans "Pending" %}</a></li>
                <li><a data-toggle="tab" href="#reviewed">{% trans "Reviewed" %}</a></li>
            </ul>
            <div class="tab-content">
                <div id="pending" class="tab-pane fade in active panel panel-default">
                    <div class="panel-body">
                        {% if applications %}
                            <table class="table">
                                <tr>
                                    <th class="text-center">{% trans "Date" %}</th>
                                    <th class="text-center">{% trans "Username" %}</th>
                                    <th class="text-center">{% trans "Main Character" %}</th>
                                    <th class="text-center">{% trans "Corporation" %}</th>
                                    <th class="text-center">{% trans "Status" %}</th>
                                    <th class="text-center">{% trans "Actions" %}</th>
                                </tr>
                                {% for app in applications %}
                                    <tr>
                                        <td class="text-center">{{ app.created }}</td>
                                        <td class="text-center">{{ app.user.username }}</td>
                                        <td class="text-center">{{ app.main_character }}</td>
                                        <td class="text-center">{{ app.form.corp.corporation_name }}</td>
                                        <td class="text-center">
                                            {% if app.approved == None %}
                                                {% if app.reviewer_str %}
                                                    <div class="label label-info">{% trans "Reviewer:" %} {{ app.reviewer_str }}</div>
                                                {% else %}
                                                    <div class="label label-warning">{% trans "Pending" %}</div>
                                                {% endif %}
                                            {% elif  app.approved == True %}
                                                <div class="label label-success">{% trans "Approved" %}</div>
                                            {% else %}
                                                <div class="label label-danger">{% trans "Rejected" %}</div>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            <a href="{% url 'hrapplications:view' app.id %}"
                                               class="btn btn-primary">
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        {% else %}
                            <div class="alert alert-warning text-center">{% trans "No pending applications." %}</div>
                        {% endif %}
                    </div>
                </div>
                <div id="reviewed" class="tab-pane fade panel panel-default">
                    <div class="panel-body">
                        {% if finished_applications %}
                            <table class="table">
                                <tr>
                                    <th class="text-center">{% trans "Date" %}</th>
                                    <th class="text-center">{% trans "Username" %}</th>
                                    <th class="text-center">{% trans "Main Character" %}</th>
                                    <th class="text-center">{% trans "Corporation" %}</th>
                                    <th class="text-center">{% trans "Status" %}</th>
                                    <th class="text-center">{% trans "Actions" %}</th>
                                </tr>
                                {% for app in finished_applications %}
                                    <tr>
                                        <td class="text-center">{{ app.created }}</td>
                                        <td class="text-center">{{ app.user.username }}</td>
                                        <td class="text-center">{{ app.main_character }}</td>
                                        <td class="text-center">{{ app.form.corp.corporation_name }}</td>
                                        <td class="text-center">
                                            {% if app.approved == None %}
                                                {% if app.reviewer_str %}
                                                    <div class="label label-info">{% trans "Reviewer:" %} {{ app.reviewer_str }}</div>
                                                {% else %}
                                                    <div class="label label-warning">{% trans "Pending" %}</div>
                                                {% endif %}
                                            {% elif  app.approved == True %}
                                                <div class="label label-success">{% trans "Approved" %}</div>
                                            {% else %}
                                                <div class="label label-danger">{% trans "Rejected" %}</div>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            <a href="{% url 'hrapplications:view' app.id %}"
                                               class="btn btn-primary">
                                                <span class="glyphicon glyphicon-eye-open"></span>
                                            </a>
                                            {% if perms.hrapplications.delete_application %}
                                                <a href="{% url 'hrapplications:remove' app.id %}"
                                                    class="btn btn-danger">
                                                    <span class="glyphicon glyphicon-remove"></span>
                                                </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        {% else %}
                            <div class="alert alert-warning text-center">{% trans "No reviewed applications." %}</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

    {% if perms.auth.human_resources %}
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                                class="sr-only">{% trans "Close" %}</span></button>
                        <h4 class="modal-title" id="myModalLabel">{% trans "Application Search" %}</h4>
                    </div>
                    <div class="modal-body">
                        <form class="form-signin" role="form"
                              action={% url 'hrapplications:search' %} method="POST">
                            {% csrf_token %}
                            {{ search_form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Search" %}</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}