allianceauth/groupmanagement/urls.py
from . import views

from django.conf.urls import include, url
app_name = 'groupmanagement'

urlpatterns = [
    url(r'^groups/', views.groups_view, name='groups'),
    url(r'^group/', include([
        url(r'^management/', views.group_management,
            name='management'),
        url(r'^membership/$', views.group_membership,
            name='membership'),
        url(r'^membership/(\w+)/$', views.group_membership_list,
            name='membership_list'),
        url(r'^membership/(\w+)/remove/(\w+)/$', views.group_membership_remove,
            name='membership_remove'),
        url(r'^request_add/(\w+)', views.group_request_add,
            name='request_add'),
        url(r'^request/accept/(\w+)', views.group_accept_request,
            name='accept_request'),
        url(r'^request/reject/(\w+)', views.group_reject_request,
            name='reject_request'),

        url(r'^request_leave/(\w+)', views.group_request_leave,
            name='request_leave'),
        url(r'leave_request/accept/(\w+)', views.group_leave_accept_request,
            name='leave_accept_request'),
        url(r'^leave_request/reject/(\w+)', views.group_leave_reject_request,
            name='leave_reject_request'),
    ])),
]

allianceauth/urls.py
import esi.urls

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

import allianceauth.authentication.views
import allianceauth.authentication.urls
import allianceauth.notifications.urls
import allianceauth.groupmanagement.urls
import allianceauth.services.urls
from allianceauth.authentication.decorators import main_character_required, decorate_url_patterns
from allianceauth import NAME
from allianceauth import views
from allianceauth.authentication import hmac_urls
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Authentication
    url(r'', include(allianceauth.authentication.urls)),
    url(r'^account/login/$', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    url(r'^account/', include(hmac_urls)),

    # Admin urls
    url(r'^admin/', admin.site.urls),

    # SSO
    url(r'^sso/', include((esi.urls, 'esi'), namespace='esi')),
    url(r'^sso/login$', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    url(r'', include(allianceauth.notifications.urls)),

    # Groups
    url(r'', include(allianceauth.groupmanagement.urls)),

    # Services
    url(r'', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    url(r'^night/', views.NightModeRedirectView.as_view(), name='nightmode')
]


# Append app urls
app_urls = get_hooks('url_hook')
for app in app_urls:
    urlpatterns += [url(r'', decorate_url_patterns([app().include_pattern], main_character_required))]

allianceauth/groupmanagement/models.py
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class GroupRequest(models.Model):
    status = models.CharField(max_length=254)
    leave_request = models.BooleanField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    @property
    def main_char(self):
        """
        Legacy property for main character
        :return: self.users main character
        """
        return self.user.profile.main_character

    def __str__(self):
        return self.user.username + ":" + self.group.name


class AuthGroup(models.Model):
    """
    Extends Django Group model with a one-to-one field
    Attributes are accessible via group as if they were in the model
    e.g. group.authgroup.internal

    Logic:
    Internal - not requestable by users, at all. Covers Corp_, Alliance_, Members etc groups.
    Groups are internal by default

    Public - Other options are respected, but any user will be able to become and remain a member, even if they
    have no API etc entered. Auth will not manage these groups automatically so user removal is up to
    group managers/leaders.

    Not Internal and:
        Hidden - users cannot view, can request if they have the direct link.
        Not Hidden - Users can view and request the group
        Open - Users are automatically accepted into the group
        Not Open - Users requests must be approved before they are added to the group
    """
    group = models.OneToOneField(Group, on_delete=models.CASCADE, primary_key=True)

    internal = models.BooleanField(default=True,
                                   help_text="Internal group, users cannot see, join or request to join this group.<br>"
                                             "Used for groups such as Members, Corp_*, Alliance_* etc.<br>"
                                             "<b>Overrides Hidden and Open options when selected.</b>")
    hidden = models.BooleanField(default=True,
                                 help_text="Group is hidden from users but can still join with the correct link.")
    open = models.BooleanField(default=False,
                               help_text="Group is open and users will be automatically added upon request. <br>"
                                         "If the group is not open users will need their request manually approved.")
    public = models.BooleanField(default=False,
                                 help_text="Group is public. Any registered user is able to join this group, with "
                                           "visibility based on the other options set for this group.<br> Auth will "
                                           "not remove users from this group automatically when they are no longer "
                                           "authenticated.")
    # Group leaders have management access to this group
    group_leaders = models.ManyToManyField(User, related_name='leads_groups', blank=True,
                                           help_text="Group leaders can process group requests for this group "
                                                     "specifically. Use the auth.group_management permission to allow "
                                                     "a user to manage all groups.")

    description = models.CharField(max_length=512, blank=True, help_text="Description of the group shown to users.")

    def __str__(self):
        return self.group.name

    class Meta:
        permissions = (
            ("request_groups", u"Can request non-public groups"),
        )
        default_permissions = tuple()


@receiver(post_save, sender=Group)
def create_auth_group(sender, instance, created, **kwargs):
    """
    Creates the AuthGroup model when a group is created
    """
    if created:
        AuthGroup.objects.create(group=instance)


@receiver(post_save, sender=Group)
def save_auth_group(sender, instance, **kwargs):
    """
    Ensures AuthGroup model is saved automatically
    """
    instance.authgroup.save()

allianceauth/groupmanagement/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import Count
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from .managers import GroupManager
from .models import GroupRequest

from allianceauth.notifications import notify

logger = logging.getLogger(__name__)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_management(request):
    logger.debug("group_management called by user %s" % request.user)
    acceptrequests = []
    leaverequests = []

    base_group_query = GroupRequest.objects.select_related('user', 'group')
    if GroupManager.has_management_permission(request.user):
        # Full access
        group_requests = base_group_query.all()
    else:
        # Group specific leader
        group_requests = base_group_query.filter(group__authgroup__group_leaders__in=[request.user])

    for grouprequest in group_requests:
        if grouprequest.leave_request:
            leaverequests.append(grouprequest)
        else:
            acceptrequests.append(grouprequest)

    logger.debug("Providing user %s with %s acceptrequests and %s leaverequests." % (
        request.user, len(acceptrequests), len(leaverequests)))

    render_items = {'acceptrequests': acceptrequests, 'leaverequests': leaverequests}

    return render(request, 'groupmanagement/index.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership(request):
    logger.debug("group_membership called by user %s" % request.user)
    # Get all open and closed groups
    if GroupManager.has_management_permission(request.user):
        # Full access
        groups = GroupManager.get_joinable_groups()
    else:
        # Group leader specific
        groups = GroupManager.get_group_leaders_groups(request.user)

    groups = groups.exclude(authgroup__internal=True).annotate(num_members=Count('user')).order_by('name')

    render_items = {'groups': groups}

    return render(request, 'groupmanagement/groupmembership.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership_list(request, group_id):
    logger.debug("group_membership_list called by user %s for group id %s" % (request.user, group_id))
    group = get_object_or_404(Group, id=group_id)
    try:

        # Check its a joinable group i.e. not corp or internal
        # And the user has permission to manage it
        if not GroupManager.joinable_group(group) or not GroupManager.can_manage_group(request.user, group):
            logger.warning("User %s attempted to view the membership of group %s but permission was denied" %
                           (request.user, group_id))
            raise PermissionDenied

    except ObjectDoesNotExist:
        raise Http404("Group does not exist")

    members = list()

    for member in group.user_set.select_related('profile').all().order_by('username'):

        members.append({
            'user': member,
            'main_char': member.profile.main_character
        })

    render_items = {'group': group, 'members': members}

    return render(request, 'groupmanagement/groupmembers.html', context=render_items)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_membership_remove(request, group_id, user_id):
    logger.debug("group_membership_remove called by user %s for group id %s on user id %s" %
                 (request.user, group_id, user_id))
    group = get_object_or_404(Group, id=group_id)
    try:
        # Check its a joinable group i.e. not corp or internal
        # And the user has permission to manage it
        if not GroupManager.joinable_group(group) or not GroupManager.can_manage_group(request.user, group):
            logger.warning("User %s attempted to remove a user from group %s but permission was denied" % (request.user,
                                                                                                           group_id))
            raise PermissionDenied

        try:
            user = group.user_set.get(id=user_id)
            # Remove group from user
            user.groups.remove(group)
            logger.info("User %s removed user %s from group %s" % (request.user, user, group))
            messages.success(request, _("Removed user %(user)s from group %(group)s.") % {"user": user, "group": group})
        except ObjectDoesNotExist:
            messages.warning(request, _("User does not exist in that group"))

    except ObjectDoesNotExist:
        messages.warning(request, _("Group does not exist"))

    return redirect('groupmanagement:membership_list', group_id)


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_accept_request(request, group_request_id):
    logger.debug("group_accept_request called by user %s for grouprequest id %s" % (request.user, group_request_id))
    group_request = get_object_or_404(GroupRequest, id=group_request_id)
    try:
        group, created = Group.objects.get_or_create(name=group_request.group.name)

        if not GroupManager.joinable_group(group_request.group) or \
                not GroupManager.can_manage_group(request.user, group_request.group):
            raise PermissionDenied

        group_request.user.groups.add(group)
        group_request.user.save()
        group_request.delete()
        logger.info("User %s accepted group request from user %s to group %s" % (
            request.user, group_request.user, group_request.group.name))
        notify(group_request.user, "Group Application Accepted", level="success",
               message="Your application to %s has been accepted." % group_request.group)
        messages.success(request,
                         _('Accepted application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})

    except PermissionDenied as p:
        logger.warning("User %s attempted to accept group join request %s but permission was denied" %
                       (request.user, group_request_id))
        raise p
    except:
        messages.error(request, _('An unhandled error occurred while processing the application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})
        logger.exception("Unhandled exception occurred while user %s attempting to accept grouprequest id %s." % (
            request.user, group_request_id))
        pass

    return redirect("groupmanagement:management")


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_reject_request(request, group_request_id):
    logger.debug("group_reject_request called by user %s for group request id %s" % (request.user, group_request_id))
    group_request = get_object_or_404(GroupRequest, id=group_request_id)
    try:
        if not GroupManager.can_manage_group(request.user, group_request.group):
            raise PermissionDenied

        if group_request:
            logger.info("User %s rejected group request from user %s to group %s" % (
                request.user, group_request.user, group_request.group.name))
            group_request.delete()
            notify(group_request.user, "Group Application Rejected", level="danger",
                   message="Your application to %s has been rejected." % group_request.group)
            messages.success(request,
                             _('Rejected application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})

    except PermissionDenied as p:
        logger.warning("User %s attempted to reject group join request %s but permission was denied" %
                       (request.user, group_request_id))
        raise p
    except:
        messages.error(request, _('An unhandled error occurred while processing the application from %(mainchar)s to %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})
        logger.exception("Unhandled exception occured while user %s attempting to reject group request id %s" % (
            request.user, group_request_id))
        pass

    return redirect("groupmanagement:management")


@login_required
@user_passes_test(GroupManager.can_manage_groups)
def group_leave_accept_request(request, group_request_id):
    logger.debug(
        "group_leave_accept_request called by user %s for group request id %s" % (request.user, group_request_id))
    group_request = get_object_or_404(GroupRequest, id=group_request_id)
    try:
        if not GroupManager.can_manage_group(request.user, group_request.group):
            raise PermissionDenied

        group, created = Group.objects.get_or_create(name=group_request.group.name)
        group_request.user.groups.remove(group)
        group_request.user.save()
        group_request.delete()
        logger.info("User %s accepted group leave request from user %s to group %s" % (
            request.user, group_request.user, group_request.group.name))
        notify(group_request.user, "Group Leave Request Accepted", level="success",
               message="Your request to leave %s has been accepted." % group_request.group)
        messages.success(request,
                         _('Accepted application from %(mainchar)s to leave %(group)s.') % {"mainchar": group_request.main_char, "group": group_request.group})
    except PermissionDenied as p:
        logger.warning("User %s attempted to accept group leave request %s but permission was denied" %
                       (request.user, group_request_id))
        raise p
    except:

allianceauth/groupmanagement/templates/groupmanagement/groupmembers.html
{% extends "allianceauth/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "Group Members" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include 'groupmanagement/menu.html' %}
        <h3>{{ group.name }} {% trans 'Members' %}</h3>
        <div id="list" class="">
            {% if group.user_set %}
            <table class="table">
                <tr>
                    <th class="text-center">{% trans "User" %}</th>
                    <th class="text-center">{% trans "Character" %}</th>
                    <th class="text-center">{% trans "Corp" %}</th>
                    <th class="text-center">{% trans "Alliance" %}</th>
                    <th class="text-center">{% trans "Action" %}</th>
                </tr>
                {% for member in members %}
                    <tr>
                        <td class="text-center">{{ member.user.username }}</td>
                        <td class="text-center">{{ member.main_char.character_name }}</td>
                        <td class="text-center">{{ member.main_char.corporation_name }}</td>
                        <td class="text-center">{{ member.main_char.alliance_name }}</td>
                        <td class="text-center">
                            <a href="{% url 'groupmanagement:membership_remove' group.id member.user.id %}" class="btn btn-danger"
                                title="{% trans "Remove from group" %}">
                                    <i class="glyphicon glyphicon-remove"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <div class="alert alert-warning text-center">{% trans "No group members to list." %}</div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

allianceauth/groupmanagement/templates/groupmanagement/groupmembership.html
{% extends "allianceauth/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "Groups Membership" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include 'groupmanagement/menu.html' %}
        <div>
            {% if groups %}
            <h3>Groups</h3>
            <table class="table">
                <tr>
                    <th class="text-center">{% trans "Name" %}</th>
                    <th class="text-center">{% trans "Description" %}</th>
                    <th class="text-center">{% trans "Status" %}</th>
                    <th class="text-center">{% trans "Member Count" %}</th>
                    <th class="text-center">{% trans "Action" %}</th>
                </tr>
                {% for group in groups %}
                    <tr>
                        <td class="text-center">{{ group.name }}</td>
                        <td class="text-center">{{ group.authgroup.description }}</td>
                        <td class="text-center">
                            {% if group.authgroup.hidden %}
                                <span class="label label-info">{% trans "Hidden" %}</span>
                            {% elif group.authgroup.open %}
                                <span class="label label-success">{% trans "Open" %}</span>
                            {% else %}
                                <span class="label label-default">{% trans "Requestable" %}</span>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            {{ group.num_members }}
                        </td>
                        <td class="text-center">
                            <a href="{% url 'groupmanagement:membership_list' group.id %}" class="btn btn-primary"
                                title="{% trans "View Members" %}">
                                    <i class="glyphicon glyphicon-eye-open"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <div class="alert alert-warning text-center">{% trans "No groups to list." %}</div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

allianceauth/groupmanagement/templates/groupmanagement/groups.html
{% extends "allianceauth/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "Available Groups" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}
url
{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Available Groups" %}</h1>
        {% if groups %}
        <table class="table">
            <tr>
                <th class="text-center">{% trans "Name" %}</th>
                <th class="text-center">{% trans "Description" %}</th>
                <th class="text-center">{% trans "Action" %}</th>
            </tr>

            {% for g in groups %}
                <tr>
                    <td class="text-center">{{ g.group.name }}</td>
                    <td class="text-center">{{ g.group.authgroup.description }}</td>
                    <td class="text-center">
                        {% if g.group in user.groups.all %}
                            {% if not g.request %}
                                <a href="{% url 'groupmanagement:request_leave' g.group.id %}" class="btn btn-danger">
                                    {% trans "Leave" %}
                                </a>
                            {% else %}
                                <button type="button" class="btn btn-primary" disabled>
                                    {{ g.request.status }}
                                </button>
                            {% endif %}
                        {% elif not g.request %}
                            <a href="{% url 'groupmanagement:request_add' g.group.id %}" class="btn btn-success">
                                {% trans "Request" %}
                            </a>
                        {% else %}
                            <button type="button" class="btn btn-primary" disabled>
                                {{ g.request.status }}
                            </button>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% else %}
        <div class="alert alert-warning text-center">{% trans "No groups available." %}</div>
        {% endif %}
    </div>

{% endblock content %}

allianceauth/groupmanagement/templates/groupmanagement/index.html
{% extends "allianceauth/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block page_title %}{% trans "Groups Management" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <br>
        {% include 'groupmanagement/menu.html' %}
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#add">{% trans "Group Add Requests" %}</a></li>
            <li><a data-toggle="tab" href="#leave">{% trans "Group Leave Requests" %}</a></li>
        </ul>
        <div class="tab-content">
            <div id="add" class="tab-pane fade in active panel panel-default">
                <div class="panel-body">
                {% if acceptrequests %}
                    <table class="table">
                        <tr>
                            <th class="text-center">{% trans "RequestID" %}</th>
                            <th class="text-center">{% trans "CharacterName" %}</th>
                            <th class="text-center">{% trans "GroupName" %}</th>
                            <th class="text-center">{% trans "Action" %}</th>
                        </tr>
                        {% for acceptrequest in acceptrequests %}
                            <tr>
                                <td class="text-center">{{ acceptrequest.id }}</td>
                                <td class="text-center">{{ acceptrequest.main_char.character_name }}</td>
                                <td class="text-center">{{ acceptrequest.group.name }}</td>
                                <td class="text-center">
                                    <a href="{% url 'groupmanagement:accept_request' acceptrequest.id %}" class="btn btn-success">
                                        {% trans "Accept" %}
                                    </a>
                                    <a href="{% url 'groupmanagement:reject_request' acceptrequest.id %}" class="btn btn-danger">
                                        {% trans "Reject" %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div class="alert alert-warning text-center">{% trans "No group add requests." %}</div>
                {% endif %}
                </div>
            </div>
            <div id="leave" class="tab-pane fade panel panel-default">
                <div class="panel-body">
                {% if leaverequests %}
                    <table class="table">
                        <tr>
                            <th class="text-center">{% trans "RequestID" %}</th>
                            <th class="text-center">{% trans "CharacterName" %}</th>
                            <th class="text-center">{% trans "GroupName" %}</th>
                            <th class="text-center">{% trans "Action" %}</th>
                        </tr>
                        {% for leaverequest in leaverequests %}
                            <tr>
                                <td class="text-center">{{ leaverequest.id }}</td>
                                <td class="text-center">{{ leaverequest.main_char.character_name }}</td>
                                <td class="text-center">{{ leaverequest.group.name }}</td>
                                <td class="text-center">
                                    <a href="{% url 'groupmanagement:leave_accept_request' leaverequest.id %}" class="btn btn-success">
                                        {% trans "Accept" %}
                                    </a>
                                    <a href="{% url 'groupmanagement:leave_reject_request' leaverequest.id %}" class="btn btn-danger">
                                        {% trans "Reject" %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div class="alert alert-warning text-center">{% trans "No group leave requests." %}</div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

allianceauth/groupmanagement/templates/groupmanagement/menu.html
{% load staticfiles %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
<div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">{% trans "Toggle navigation" %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">{% trans "Group Management" %}</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="{% navactive request 'auth_group_management' %}">
                <a href="{% url 'groupmanagement:management' %}">{% trans "Group Requests" %}</a>
            </li>
            <li class="{% navactive request 'auth_group_membership auth_group_membership_list' %}">
                <a href="{% url 'groupmanagement:membership' %}">{% trans "Group Membership" %}</a>
            </li>
        </ul>
    </div>
</div>
</nav>